{% set name = "pysoundfile" %}
{% set pypi_name = "SoundFile" %}
{% set version = "0.10.3.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 490cff42650733d1832728b937fe99fa1802896f5ef4d61bcf78cf7ebecb107b

build:
  number: 0
  noarch: python
  script:
    - export PYSOUNDFILE_PLATFORM=win32
    - python -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - cffi
  run:
    - python
    - cffi
    - numpy
    - libsndfile

test:
  imports:
    - soundfile

about:
  home: http://pysoundfile.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SoundFile is an audio library based on libsndfile, CFFI, and NumPy'
  dev_url: https://github.com/bastibe/SoundFile

extra:
  recipe-maintainers:
    - scopatz
    - wolfv
