{% set name = "pysoundfile" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[2] }}/{{ name[2:] }}/{{ name[2:] }}-{{ version }}.tar.gz
  sha256: b2c68dab1e30297317080a5b43df57e302584c49e2942defdde0acccc53f0e5b
  patches:
    - patches/0001-unvendoring-libsndfile.patch
    - patches/0002-platform-tag-fix.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - setuptools
    - wheel
    - cffi
  run:
    - python
    - cffi
    # numpy is optional, but from the readme it seems
    # needed
    - numpy
    - libsndfile >=1.2

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  imports:
    - soundfile
  commands:
    - pip check
    # Verify that soundfile is linking the correct libsndfile object
    # - linux: libsndfile.so / libsndfile.so.1
    # - osx: libsndfile.dylib
    # - win: sndfile.dll
    - python -c "import soundfile; from pathlib import Path; print(soundfile._libname); assert('sndfile' in Path(soundfile._libname).stem)"
    - pytest -vv .

about:
  home: https://python-soundfile.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SoundFile is an audio library based on libsndfile, CFFI, and NumPy'
  description: |
    The soundfile module can read and write sound files. File reading/writing is 
    supported through libsndfile, which is a free, cross-platform, open-source 
    (LGPL) library for reading and writing many different sampled sound file formats 
    that runs on many platforms including Windows, OS X, and Unix
  dev_url: https://github.com/bastibe/python-soundfile
  doc_url: https://python-soundfile.readthedocs.io

extra:
  recipe-maintainers:
    - scopatz
    - wolfv
    - bmcfee
