{% set name = "pysoundfile" %}
{% set pypi_name = "soundfile" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: e8e1017b2cf1dda767aef19d2fd9ee5ebe07e050d430f77a0a7c66ba08b8cdae

build:
  number: 0
  script:
    # We are currently building a noarch package, but pysoundfile contains a
    # install-time check for the OS and injects the sf_wchar_open function
    # conditionally. If this variable is not set, opening files on Windows doesn't work
    # Fix coming hopefully with https://github.com/bastibe/python-soundfile/pull/288
    # Original issue on conda-forge: https://github.com/conda-forge/libsndfile-feedstock/issues/14
    - export PYSOUNDFILE_PLATFORM=win32
    - python -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36 or s390x or win]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - cffi
  run:
    - python
    - cffi
    - numpy
    - libsndfile >=1.2

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - soundfile
  commands:
    # Verify that soundfile is linking the correct libsndfile object
     - python -c "import soundfile; print(soundfile._libname)"
     - pytest -vv . -k "not (test_available_formats or test_available_subtypes)"


about:
  home: https://python-soundfile.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SoundFile is an audio library based on libsndfile, CFFI, and NumPy'
  description: |
    The soundfile module can read and write sound files. File reading/writing is 
    supported through libsndfile, which is a free, cross-platform, open-source 
    (LGPL) library for reading and writing many different sampled sound file formats 
    that runs on many platforms including Windows, OS X, and Unix
  dev_url: https://github.com/bastibe/python-soundfile
  doc_url: https://python-soundfile.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - scopatz
    - wolfv
    - bmcfee
