{% set name = "pysoundfile" %}
{% set pypi_name = "soundfile" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: e8e1017b2cf1dda767aef19d2fd9ee5ebe07e050d430f77a0a7c66ba08b8cdae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36 or s390x or win]
  patches:
    - patches/0001-unvendoring-libsndfile.patch

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - setuptools
    - wheel
    - cffi
  run:
    - python
    - cffi
    - numpy
    - libsndfile >=1.2

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip <24.2
  imports:
    - soundfile
  commands:
    - pip check
    # Verify that soundfile is linking the correct libsndfile object
    # - on linux-64: libsndfile.so.1
    # - on osx libsndfile.dylib
    # - on linux-aarch64: libsndfile.so
    # - we do not build for win, otherwise it would be libsndfile.dll
    - python -c "import soundfile; from pathlib import Path; print(soundfile._libname); assert('libsndfile' in Path(soundfile._libname).stem)"
    - pytest -vv .

about:
  home: https://python-soundfile.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SoundFile is an audio library based on libsndfile, CFFI, and NumPy'
  description: |
    The soundfile module can read and write sound files. File reading/writing is 
    supported through libsndfile, which is a free, cross-platform, open-source 
    (LGPL) library for reading and writing many different sampled sound file formats 
    that runs on many platforms including Windows, OS X, and Unix
  dev_url: https://github.com/bastibe/python-soundfile
  doc_url: https://python-soundfile.readthedocs.io

extra:
  recipe-maintainers:
    - scopatz
    - wolfv
    - bmcfee
