travis:
  secure:
    BINSTAR_TOKEN: LD3Wm6FsnWr86McErGPFMWCgYLexGWlrz+sVZ/QoC7UXf+CvS4nW5v5dkljJUEp8AHr9U4EnvtUgRtJmQNJxhChFsVOjt7i64erxCE+cEb2sC2Ny/0Rmy4PlxFf2aLF/vWK5jYdrfPfqdXZYyuEy68wioeSeupn/vHCRpoiUrQZDmz/Vm1wLEhxlv5oG7rO64QcTFyJulEdKBME+1rKRq13MPDI9g8RJGx3cdTACyCYq9lLyYanzgFWxi4BkL8s29AcEeu6Y6NLBv939H+a+ADhiVXebjKOSIRGxcj9TLl6R5b7GbFazOsyJ1qaNv5Aw+HN/mMyc/9Su+qkSaIVoQwdLyBPa3sR846qxhJwucOtRy3w2CYTKTMwmT40YLKgi8wTMczM9dZCbbEUz6qJMuRc2X52uJClLbXKXnsN+0I8hlgT+43wjT9zISni99JZZYDOXc0yi0PtPPTmiZBAUbmbG1m6OmJMQPiP87hOeHb8mfOQcPVAAqMtHaUBunzIlewQrmE+FCtuFWqyp6POBdf19+4eSVy7heSbdIyCV5rdpJR6/M/VcuPwwsOoTUN5JdV9svzvTNXbOADt3wDHxm7FH8RcmEVdcVhOUeYXEinrWBnuZOvP+j+567/VtpkZrAWq6C+E+dD24Hy8+NaXGVDHZ2CDXnIqDCxZ6Yk+jD8c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
